# -*- coding: utf-8 -*-
"""Discovering vowel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tE2dvSgmtDh4BceROXYafPSZYvxMg0qR
"""

listaVogais = ['a','e','i','o','u']
qtdeVogais = 0
nome = input("Informe seu nome: ")

for letra in nome:

  if(letra.lower() in listaVogais):
    qtdeVogais += 1

print(f"Esse nome tem: {qtdeVogais} vogais")